name: Build PanelDue Firmware

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM Compiler & CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi cmake ninja-build

      - name: Configure and Build
        run: |
          cmake -B build -G "Ninja" -DDEVICE=v3-4.3
          cmake --build build

      - name: Upload Binary Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PanelDueFirmware-Binaries
          path: |
            build/*.bin
            **/*.bin
